Module(body=[
  Expr(value=Str(s='\n#Sequence to sequence example in Keras (character-level).\n\nThis script demonstrates how to implement a basic character-level\nsequence-to-sequence model. We apply it to translating\nshort English sentences into short French sentences,\ncharacter-by-character. Note that it is fairly unusual to\ndo character-level machine translation, as word-level\nmodels are more common in this domain.\n\n**Summary of the algorithm**\n\n- We start with input sequences from a domain (e.g. English sentences)\n    and corresponding target sequences from another domain\n    (e.g. French sentences).\n- An encoder LSTM turns input sequences to 2 state vectors\n    (we keep the last LSTM state and discard the outputs).\n- A decoder LSTM is trained to turn the target sequences into\n    the same sequence but offset by one timestep in the future,\n    a training process called "teacher forcing" in this context.\n    It uses as initial state the state vectors from the encoder.\n    Effectively, the decoder learns to generate `targets[t+1...]`\n    given `targets[...t]`, conditioned on the input sequence.\n- In inference mode, when we want to decode unknown input sequences, we:\n    - Encode the input sequence into state vectors\n    - Start with a target sequence of size 1\n        (just the start-of-sequence character)\n    - Feed the state vectors and 1-char target sequence\n        to the decoder to produce predictions for the next character\n    - Sample the next character using these predictions\n        (we simply use argmax).\n    - Append the sampled character to the target sequence\n    - Repeat until we generate the end-of-sequence character or we\n        hit the character limit.\n\n**Data download**\n\n[English to French sentence pairs.\n](http://www.manythings.org/anki/fra-eng.zip)\n\n[Lots of neat sentence pairs datasets.\n](http://www.manythings.org/anki/)\n\n**References**\n\n- [Sequence to Sequence Learning with Neural Networks\n   ](https://arxiv.org/abs/1409.3215)\n- [Learning Phrase Representations using\n    RNN Encoder-Decoder for Statistical Machine Translation\n    ](https://arxiv.org/abs/1406.1078)\n')),
  ImportFrom(
    module='__future__',
    names=[alias(
      name='print_function',
      asname=None)],
    level=0),
  ImportFrom(
    module='keras.models',
    names=[alias(
      name='Model',
      asname=None)],
    level=0),
  ImportFrom(
    module='keras.layers',
    names=[
      alias(
        name='Input',
        asname=None),
      alias(
        name='LSTM',
        asname=None),
      alias(
        name='Dense',
        asname=None)],
    level=0),
  Import(names=[alias(
    name='numpy',
    asname='np')]),
  Assign(
    targets=[Name(
      id='batch_size',
      ctx=Store())],
    value=Num(n=64)),
  Assign(
    targets=[Name(
      id='epochs',
      ctx=Store())],
    value=Num(n=100)),
  Assign(
    targets=[Name(
      id='latent_dim',
      ctx=Store())],
    value=Num(n=256)),
  Assign(
    targets=[Name(
      id='num_samples',
      ctx=Store())],
    value=Num(n=10000)),
  Assign(
    targets=[Name(
      id='data_path',
      ctx=Store())],
    value=Str(s='fra-eng/fra.txt')),
  Assign(
    targets=[Name(
      id='input_texts',
      ctx=Store())],
    value=List(
      elts=[],
      ctx=Load())),
  Assign(
    targets=[Name(
      id='target_texts',
      ctx=Store())],
    value=List(
      elts=[],
      ctx=Load())),
  Assign(
    targets=[Name(
      id='input_characters',
      ctx=Store())],
    value=Call(
      func=Name(
        id='set',
        ctx=Load()),
      args=[],
      keywords=[])),
  Assign(
    targets=[Name(
      id='target_characters',
      ctx=Store())],
    value=Call(
      func=Name(
        id='set',
        ctx=Load()),
      args=[],
      keywords=[])),
  With(
    items=[withitem(
      context_expr=Call(
        func=Name(
          id='open',
          ctx=Load()),
        args=[
          Name(
            id='data_path',
            ctx=Load()),
          Str(s='r')],
        keywords=[keyword(
          arg='encoding',
          value=Str(s='utf-8'))]),
      optional_vars=Name(
        id='f',
        ctx=Store()))],
    body=[Assign(
      targets=[Name(
        id='lines',
        ctx=Store())],
      value=Call(
        func=Attribute(
          value=Call(
            func=Attribute(
              value=Name(
                id='f',
                ctx=Load()),
              attr='read',
              ctx=Load()),
            args=[],
            keywords=[]),
          attr='split',
          ctx=Load()),
        args=[Str(s='\n')],
        keywords=[]))]),
  For(
    target=Name(
      id='line',
      ctx=Store()),
    iter=Subscript(
      value=Name(
        id='lines',
        ctx=Load()),
      slice=Slice(
        lower=None,
        upper=Call(
          func=Name(
            id='min',
            ctx=Load()),
          args=[
            Name(
              id='num_samples',
              ctx=Load()),
            BinOp(
              left=Call(
                func=Name(
                  id='len',
                  ctx=Load()),
                args=[Name(
                  id='lines',
                  ctx=Load())],
                keywords=[]),
              op=Sub(),
              right=Num(n=1))],
          keywords=[]),
        step=None),
      ctx=Load()),
    body=[
      Assign(
        targets=[Tuple(
          elts=[
            Name(
              id='input_text',
              ctx=Store()),
            Name(
              id='target_text',
              ctx=Store())],
          ctx=Store())],
        value=Call(
          func=Attribute(
            value=Name(
              id='line',
              ctx=Load()),
            attr='split',
            ctx=Load()),
          args=[Str(s='\t')],
          keywords=[])),
      Assign(
        targets=[Name(
          id='target_text',
          ctx=Store())],
        value=BinOp(
          left=BinOp(
            left=Str(s='\t'),
            op=Add(),
            right=Name(
              id='target_text',
              ctx=Load())),
          op=Add(),
          right=Str(s='\n'))),
      Expr(value=Call(
        func=Attribute(
          value=Name(
            id='input_texts',
            ctx=Load()),
          attr='append',
          ctx=Load()),
        args=[Name(
          id='input_text',
          ctx=Load())],
        keywords=[])),
      Expr(value=Call(
        func=Attribute(
          value=Name(
            id='target_texts',
            ctx=Load()),
          attr='append',
          ctx=Load()),
        args=[Name(
          id='target_text',
          ctx=Load())],
        keywords=[])),
      For(
        target=Name(
          id='char',
          ctx=Store()),
        iter=Name(
          id='input_text',
          ctx=Load()),
        body=[If(
          test=Compare(
            left=Name(
              id='char',
              ctx=Load()),
            ops=[NotIn()],
            comparators=[Name(
              id='input_characters',
              ctx=Load())]),
          body=[Expr(value=Call(
            func=Attribute(
              value=Name(
                id='input_characters',
                ctx=Load()),
              attr='add',
              ctx=Load()),
            args=[Name(
              id='char',
              ctx=Load())],
            keywords=[]))],
          orelse=[])],
        orelse=[]),
      For(
        target=Name(
          id='char',
          ctx=Store()),
        iter=Name(
          id='target_text',
          ctx=Load()),
        body=[If(
          test=Compare(
            left=Name(
              id='char',
              ctx=Load()),
            ops=[NotIn()],
            comparators=[Name(
              id='target_characters',
              ctx=Load())]),
          body=[Expr(value=Call(
            func=Attribute(
              value=Name(
                id='target_characters',
                ctx=Load()),
              attr='add',
              ctx=Load()),
            args=[Name(
              id='char',
              ctx=Load())],
            keywords=[]))],
          orelse=[])],
        orelse=[])],
    orelse=[]),
  Assign(
    targets=[Name(
      id='input_characters',
      ctx=Store())],
    value=Call(
      func=Name(
        id='sorted',
        ctx=Load()),
      args=[Call(
        func=Name(
          id='list',
          ctx=Load()),
        args=[Name(
          id='input_characters',
          ctx=Load())],
        keywords=[])],
      keywords=[])),
  Assign(
    targets=[Name(
      id='target_characters',
      ctx=Store())],
    value=Call(
      func=Name(
        id='sorted',
        ctx=Load()),
      args=[Call(
        func=Name(
          id='list',
          ctx=Load()),
        args=[Name(
          id='target_characters',
          ctx=Load())],
        keywords=[])],
      keywords=[])),
  Assign(
    targets=[Name(
      id='num_encoder_tokens',
      ctx=Store())],
    value=Call(
      func=Name(
        id='len',
        ctx=Load()),
      args=[Name(
        id='input_characters',
        ctx=Load())],
      keywords=[])),
  Assign(
    targets=[Name(
      id='num_decoder_tokens',
      ctx=Store())],
    value=Call(
      func=Name(
        id='len',
        ctx=Load()),
      args=[Name(
        id='target_characters',
        ctx=Load())],
      keywords=[])),
  Assign(
    targets=[Name(
      id='max_encoder_seq_length',
      ctx=Store())],
    value=Call(
      func=Name(
        id='max',
        ctx=Load()),
      args=[ListComp(
        elt=Call(
          func=Name(
            id='len',
            ctx=Load()),
          args=[Name(
            id='txt',
            ctx=Load())],
          keywords=[]),
        generators=[comprehension(
          target=Name(
            id='txt',
            ctx=Store()),
          iter=Name(
            id='input_texts',
            ctx=Load()),
          ifs=[],
          is_async=0)])],
      keywords=[])),
  Assign(
    targets=[Name(
      id='max_decoder_seq_length',
      ctx=Store())],
    value=Call(
      func=Name(
        id='max',
        ctx=Load()),
      args=[ListComp(
        elt=Call(
          func=Name(
            id='len',
            ctx=Load()),
          args=[Name(
            id='txt',
            ctx=Load())],
          keywords=[]),
        generators=[comprehension(
          target=Name(
            id='txt',
            ctx=Store()),
          iter=Name(
            id='target_texts',
            ctx=Load()),
          ifs=[],
          is_async=0)])],
      keywords=[])),
  Expr(value=Call(
    func=Name(
      id='print',
      ctx=Load()),
    args=[
      Str(s='Number of samples:'),
      Call(
        func=Name(
          id='len',
          ctx=Load()),
        args=[Name(
          id='input_texts',
          ctx=Load())],
        keywords=[])],
    keywords=[])),
  Expr(value=Call(
    func=Name(
      id='print',
      ctx=Load()),
    args=[
      Str(s='Number of unique input tokens:'),
      Name(
        id='num_encoder_tokens',
        ctx=Load())],
    keywords=[])),
  Expr(value=Call(
    func=Name(
      id='print',
      ctx=Load()),
    args=[
      Str(s='Number of unique output tokens:'),
      Name(
        id='num_decoder_tokens',
        ctx=Load())],
    keywords=[])),
  Expr(value=Call(
    func=Name(
      id='print',
      ctx=Load()),
    args=[
      Str(s='Max sequence length for inputs:'),
      Name(
        id='max_encoder_seq_length',
        ctx=Load())],
    keywords=[])),
  Expr(value=Call(
    func=Name(
      id='print',
      ctx=Load()),
    args=[
      Str(s='Max sequence length for outputs:'),
      Name(
        id='max_decoder_seq_length',
        ctx=Load())],
    keywords=[])),
  Assign(
    targets=[Name(
      id='input_token_index',
      ctx=Store())],
    value=Call(
      func=Name(
        id='dict',
        ctx=Load()),
      args=[ListComp(
        elt=Tuple(
          elts=[
            Name(
              id='char',
              ctx=Load()),
            Name(
              id='i',
              ctx=Load())],
          ctx=Load()),
        generators=[comprehension(
          target=Tuple(
            elts=[
              Name(
                id='i',
                ctx=Store()),
              Name(
                id='char',
                ctx=Store())],
            ctx=Store()),
          iter=Call(
            func=Name(
              id='enumerate',
              ctx=Load()),
            args=[Name(
              id='input_characters',
              ctx=Load())],
            keywords=[]),
          ifs=[],
          is_async=0)])],
      keywords=[])),
  Assign(
    targets=[Name(
      id='target_token_index',
      ctx=Store())],
    value=Call(
      func=Name(
        id='dict',
        ctx=Load()),
      args=[ListComp(
        elt=Tuple(
          elts=[
            Name(
              id='char',
              ctx=Load()),
            Name(
              id='i',
              ctx=Load())],
          ctx=Load()),
        generators=[comprehension(
          target=Tuple(
            elts=[
              Name(
                id='i',
                ctx=Store()),
              Name(
                id='char',
                ctx=Store())],
            ctx=Store()),
          iter=Call(
            func=Name(
              id='enumerate',
              ctx=Load()),
            args=[Name(
              id='target_characters',
              ctx=Load())],
            keywords=[]),
          ifs=[],
          is_async=0)])],
      keywords=[])),
  Assign(
    targets=[Name(
      id='encoder_input_data',
      ctx=Store())],
    value=Call(
      func=Attribute(
        value=Name(
          id='np',
          ctx=Load()),
        attr='zeros',
        ctx=Load()),
      args=[Tuple(
        elts=[
          Call(
            func=Name(
              id='len',
              ctx=Load()),
            args=[Name(
              id='input_texts',
              ctx=Load())],
            keywords=[]),
          Name(
            id='max_encoder_seq_length',
            ctx=Load()),
          Name(
            id='num_encoder_tokens',
            ctx=Load())],
        ctx=Load())],
      keywords=[keyword(
        arg='dtype',
        value=Str(s='float32'))])),
  Assign(
    targets=[Name(
      id='decoder_input_data',
      ctx=Store())],
    value=Call(
      func=Attribute(
        value=Name(
          id='np',
          ctx=Load()),
        attr='zeros',
        ctx=Load()),
      args=[Tuple(
        elts=[
          Call(
            func=Name(
              id='len',
              ctx=Load()),
            args=[Name(
              id='input_texts',
              ctx=Load())],
            keywords=[]),
          Name(
            id='max_decoder_seq_length',
            ctx=Load()),
          Name(
            id='num_decoder_tokens',
            ctx=Load())],
        ctx=Load())],
      keywords=[keyword(
        arg='dtype',
        value=Str(s='float32'))])),
  Assign(
    targets=[Name(
      id='decoder_target_data',
      ctx=Store())],
    value=Call(
      func=Attribute(
        value=Name(
          id='np',
          ctx=Load()),
        attr='zeros',
        ctx=Load()),
      args=[Tuple(
        elts=[
          Call(
            func=Name(
              id='len',
              ctx=Load()),
            args=[Name(
              id='input_texts',
              ctx=Load())],
            keywords=[]),
          Name(
            id='max_decoder_seq_length',
            ctx=Load()),
          Name(
            id='num_decoder_tokens',
            ctx=Load())],
        ctx=Load())],
      keywords=[keyword(
        arg='dtype',
        value=Str(s='float32'))])),
  For(
    target=Tuple(
      elts=[
        Name(
          id='i',
          ctx=Store()),
        Tuple(
          elts=[
            Name(
              id='input_text',
              ctx=Store()),
            Name(
              id='target_text',
              ctx=Store())],
          ctx=Store())],
      ctx=Store()),
    iter=Call(
      func=Name(
        id='enumerate',
        ctx=Load()),
      args=[Call(
        func=Name(
          id='zip',
          ctx=Load()),
        args=[
          Name(
            id='input_texts',
            ctx=Load()),
          Name(
            id='target_texts',
            ctx=Load())],
        keywords=[])],
      keywords=[]),
    body=[
      For(
        target=Tuple(
          elts=[
            Name(
              id='t',
              ctx=Store()),
            Name(
              id='char',
              ctx=Store())],
          ctx=Store()),
        iter=Call(
          func=Name(
            id='enumerate',
            ctx=Load()),
          args=[Name(
            id='input_text',
            ctx=Load())],
          keywords=[]),
        body=[Assign(
          targets=[Subscript(
            value=Name(
              id='encoder_input_data',
              ctx=Load()),
            slice=Index(value=Tuple(
              elts=[
                Name(
                  id='i',
                  ctx=Load()),
                Name(
                  id='t',
                  ctx=Load()),
                Subscript(
                  value=Name(
                    id='input_token_index',
                    ctx=Load()),
                  slice=Index(value=Name(
                    id='char',
                    ctx=Load())),
                  ctx=Load())],
              ctx=Load())),
            ctx=Store())],
          value=Num(n=1.0))],
        orelse=[]),
      Assign(
        targets=[Subscript(
          value=Name(
            id='encoder_input_data',
            ctx=Load()),
          slice=ExtSlice(dims=[
            Index(value=Name(
              id='i',
              ctx=Load())),
            Slice(
              lower=BinOp(
                left=Name(
                  id='t',
                  ctx=Load()),
                op=Add(),
                right=Num(n=1)),
              upper=None,
              step=None),
            Index(value=Subscript(
              value=Name(
                id='input_token_index',
                ctx=Load()),
              slice=Index(value=Str(s=' ')),
              ctx=Load()))]),
          ctx=Store())],
        value=Num(n=1.0)),
      For(
        target=Tuple(
          elts=[
            Name(
              id='t',
              ctx=Store()),
            Name(
              id='char',
              ctx=Store())],
          ctx=Store()),
        iter=Call(
          func=Name(
            id='enumerate',
            ctx=Load()),
          args=[Name(
            id='target_text',
            ctx=Load())],
          keywords=[]),
        body=[
          Assign(
            targets=[Subscript(
              value=Name(
                id='decoder_input_data',
                ctx=Load()),
              slice=Index(value=Tuple(
                elts=[
                  Name(
                    id='i',
                    ctx=Load()),
                  Name(
                    id='t',
                    ctx=Load()),
                  Subscript(
                    value=Name(
                      id='target_token_index',
                      ctx=Load()),
                    slice=Index(value=Name(
                      id='char',
                      ctx=Load())),
                    ctx=Load())],
                ctx=Load())),
              ctx=Store())],
            value=Num(n=1.0)),
          If(
            test=Compare(
              left=Name(
                id='t',
                ctx=Load()),
              ops=[Gt()],
              comparators=[Num(n=0)]),
            body=[Assign(
              targets=[Subscript(
                value=Name(
                  id='decoder_target_data',
                  ctx=Load()),
                slice=Index(value=Tuple(
                  elts=[
                    Name(
                      id='i',
                      ctx=Load()),
                    BinOp(
                      left=Name(
                        id='t',
                        ctx=Load()),
                      op=Sub(),
                      right=Num(n=1)),
                    Subscript(
                      value=Name(
                        id='target_token_index',
                        ctx=Load()),
                      slice=Index(value=Name(
                        id='char',
                        ctx=Load())),
                      ctx=Load())],
                  ctx=Load())),
                ctx=Store())],
              value=Num(n=1.0))],
            orelse=[])],
        orelse=[]),
      Assign(
        targets=[Subscript(
          value=Name(
            id='decoder_input_data',
            ctx=Load()),
          slice=ExtSlice(dims=[
            Index(value=Name(
              id='i',
              ctx=Load())),
            Slice(
              lower=BinOp(
                left=Name(
                  id='t',
                  ctx=Load()),
                op=Add(),
                right=Num(n=1)),
              upper=None,
              step=None),
            Index(value=Subscript(
              value=Name(
                id='target_token_index',
                ctx=Load()),
              slice=Index(value=Str(s=' ')),
              ctx=Load()))]),
          ctx=Store())],
        value=Num(n=1.0)),
      Assign(
        targets=[Subscript(
          value=Name(
            id='decoder_target_data',
            ctx=Load()),
          slice=ExtSlice(dims=[
            Index(value=Name(
              id='i',
              ctx=Load())),
            Slice(
              lower=Name(
                id='t',
                ctx=Load()),
              upper=None,
              step=None),
            Index(value=Subscript(
              value=Name(
                id='target_token_index',
                ctx=Load()),
              slice=Index(value=Str(s=' ')),
              ctx=Load()))]),
          ctx=Store())],
        value=Num(n=1.0))],
    orelse=[]),
  Assign(
    targets=[Name(
      id='encoder_inputs',
      ctx=Store())],
    value=Call(
      func=Name(
        id='Input',
        ctx=Load()),
      args=[],
      keywords=[keyword(
        arg='shape',
        value=Tuple(
          elts=[
            NameConstant(value=None),
            Name(
              id='num_encoder_tokens',
              ctx=Load())],
          ctx=Load()))])),
  Assign(
    targets=[Name(
      id='encoder',
      ctx=Store())],
    value=Call(
      func=Name(
        id='LSTM',
        ctx=Load()),
      args=[Name(
        id='latent_dim',
        ctx=Load())],
      keywords=[keyword(
        arg='return_state',
        value=NameConstant(value=True))])),
  Assign(
    targets=[Tuple(
      elts=[
        Name(
          id='encoder_outputs',
          ctx=Store()),
        Name(
          id='state_h',
          ctx=Store()),
        Name(
          id='state_c',
          ctx=Store())],
      ctx=Store())],
    value=Call(
      func=Name(
        id='encoder',
        ctx=Load()),
      args=[Name(
        id='encoder_inputs',
        ctx=Load())],
      keywords=[])),
  Assign(
    targets=[Name(
      id='encoder_states',
      ctx=Store())],
    value=List(
      elts=[
        Name(
          id='state_h',
          ctx=Load()),
        Name(
          id='state_c',
          ctx=Load())],
      ctx=Load())),
  Assign(
    targets=[Name(
      id='decoder_inputs',
      ctx=Store())],
    value=Call(
      func=Name(
        id='Input',
        ctx=Load()),
      args=[],
      keywords=[keyword(
        arg='shape',
        value=Tuple(
          elts=[
            NameConstant(value=None),
            Name(
              id='num_decoder_tokens',
              ctx=Load())],
          ctx=Load()))])),
  Assign(
    targets=[Name(
      id='decoder_lstm',
      ctx=Store())],
    value=Call(
      func=Name(
        id='LSTM',
        ctx=Load()),
      args=[Name(
        id='latent_dim',
        ctx=Load())],
      keywords=[
        keyword(
          arg='return_sequences',
          value=NameConstant(value=True)),
        keyword(
          arg='return_state',
          value=NameConstant(value=True))])),
  Assign(
    targets=[Tuple(
      elts=[
        Name(
          id='decoder_outputs',
          ctx=Store()),
        Name(
          id='_',
          ctx=Store()),
        Name(
          id='_',
          ctx=Store())],
      ctx=Store())],
    value=Call(
      func=Name(
        id='decoder_lstm',
        ctx=Load()),
      args=[Name(
        id='decoder_inputs',
        ctx=Load())],
      keywords=[keyword(
        arg='initial_state',
        value=Name(
          id='encoder_states',
          ctx=Load()))])),
  Assign(
    targets=[Name(
      id='decoder_dense',
      ctx=Store())],
    value=Call(
      func=Name(
        id='Dense',
        ctx=Load()),
      args=[Name(
        id='num_decoder_tokens',
        ctx=Load())],
      keywords=[keyword(
        arg='activation',
        value=Str(s='softmax'))])),
  Assign(
    targets=[Name(
      id='decoder_outputs',
      ctx=Store())],
    value=Call(
      func=Name(
        id='decoder_dense',
        ctx=Load()),
      args=[Name(
        id='decoder_outputs',
        ctx=Load())],
      keywords=[])),
  Assign(
    targets=[Name(
      id='model',
      ctx=Store())],
    value=Call(
      func=Name(
        id='Model',
        ctx=Load()),
      args=[
        List(
          elts=[
            Name(
              id='encoder_inputs',
              ctx=Load()),
            Name(
              id='decoder_inputs',
              ctx=Load())],
          ctx=Load()),
        Name(
          id='decoder_outputs',
          ctx=Load())],
      keywords=[])),
  Expr(value=Call(
    func=Attribute(
      value=Name(
        id='model',
        ctx=Load()),
      attr='compile',
      ctx=Load()),
    args=[],
    keywords=[
      keyword(
        arg='optimizer',
        value=Str(s='rmsprop')),
      keyword(
        arg='loss',
        value=Str(s='categorical_crossentropy')),
      keyword(
        arg='metrics',
        value=List(
          elts=[Str(s='accuracy')],
          ctx=Load()))])),
  Expr(value=Call(
    func=Attribute(
      value=Name(
        id='model',
        ctx=Load()),
      attr='fit',
      ctx=Load()),
    args=[
      List(
        elts=[
          Name(
            id='encoder_input_data',
            ctx=Load()),
          Name(
            id='decoder_input_data',
            ctx=Load())],
        ctx=Load()),
      Name(
        id='decoder_target_data',
        ctx=Load())],
    keywords=[
      keyword(
        arg='batch_size',
        value=Name(
          id='batch_size',
          ctx=Load())),
      keyword(
        arg='epochs',
        value=Name(
          id='epochs',
          ctx=Load())),
      keyword(
        arg='validation_split',
        value=Num(n=0.2))])),
  Expr(value=Call(
    func=Attribute(
      value=Name(
        id='model',
        ctx=Load()),
      attr='save',
      ctx=Load()),
    args=[Str(s='s2s.h5')],
    keywords=[])),
  Assign(
    targets=[Name(
      id='encoder_model',
      ctx=Store())],
    value=Call(
      func=Name(
        id='Model',
        ctx=Load()),
      args=[
        Name(
          id='encoder_inputs',
          ctx=Load()),
        Name(
          id='encoder_states',
          ctx=Load())],
      keywords=[])),
  Assign(
    targets=[Name(
      id='decoder_state_input_h',
      ctx=Store())],
    value=Call(
      func=Name(
        id='Input',
        ctx=Load()),
      args=[],
      keywords=[keyword(
        arg='shape',
        value=Tuple(
          elts=[Name(
            id='latent_dim',
            ctx=Load())],
          ctx=Load()))])),
  Assign(
    targets=[Name(
      id='decoder_state_input_c',
      ctx=Store())],
    value=Call(
      func=Name(
        id='Input',
        ctx=Load()),
      args=[],
      keywords=[keyword(
        arg='shape',
        value=Tuple(
          elts=[Name(
            id='latent_dim',
            ctx=Load())],
          ctx=Load()))])),
  Assign(
    targets=[Name(
      id='decoder_states_inputs',
      ctx=Store())],
    value=List(
      elts=[
        Name(
          id='decoder_state_input_h',
          ctx=Load()),
        Name(
          id='decoder_state_input_c',
          ctx=Load())],
      ctx=Load())),
  Assign(
    targets=[Tuple(
      elts=[
        Name(
          id='decoder_outputs',
          ctx=Store()),
        Name(
          id='state_h',
          ctx=Store()),
        Name(
          id='state_c',
          ctx=Store())],
      ctx=Store())],
    value=Call(
      func=Name(
        id='decoder_lstm',
        ctx=Load()),
      args=[Name(
        id='decoder_inputs',
        ctx=Load())],
      keywords=[keyword(
        arg='initial_state',
        value=Name(
          id='decoder_states_inputs',
          ctx=Load()))])),
  Assign(
    targets=[Name(
      id='decoder_states',
      ctx=Store())],
    value=List(
      elts=[
        Name(
          id='state_h',
          ctx=Load()),
        Name(
          id='state_c',
          ctx=Load())],
      ctx=Load())),
  Assign(
    targets=[Name(
      id='decoder_outputs',
      ctx=Store())],
    value=Call(
      func=Name(
        id='decoder_dense',
        ctx=Load()),
      args=[Name(
        id='decoder_outputs',
        ctx=Load())],
      keywords=[])),
  Assign(
    targets=[Name(
      id='decoder_model',
      ctx=Store())],
    value=Call(
      func=Name(
        id='Model',
        ctx=Load()),
      args=[
        BinOp(
          left=List(
            elts=[Name(
              id='decoder_inputs',
              ctx=Load())],
            ctx=Load()),
          op=Add(),
          right=Name(
            id='decoder_states_inputs',
            ctx=Load())),
        BinOp(
          left=List(
            elts=[Name(
              id='decoder_outputs',
              ctx=Load())],
            ctx=Load()),
          op=Add(),
          right=Name(
            id='decoder_states',
            ctx=Load()))],
      keywords=[])),
  Assign(
    targets=[Name(
      id='reverse_input_char_index',
      ctx=Store())],
    value=Call(
      func=Name(
        id='dict',
        ctx=Load()),
      args=[GeneratorExp(
        elt=Tuple(
          elts=[
            Name(
              id='i',
              ctx=Load()),
            Name(
              id='char',
              ctx=Load())],
          ctx=Load()),
        generators=[comprehension(
          target=Tuple(
            elts=[
              Name(
                id='char',
                ctx=Store()),
              Name(
                id='i',
                ctx=Store())],
            ctx=Store()),
          iter=Call(
            func=Attribute(
              value=Name(
                id='input_token_index',
                ctx=Load()),
              attr='items',
              ctx=Load()),
            args=[],
            keywords=[]),
          ifs=[],
          is_async=0)])],
      keywords=[])),
  Assign(
    targets=[Name(
      id='reverse_target_char_index',
      ctx=Store())],
    value=Call(
      func=Name(
        id='dict',
        ctx=Load()),
      args=[GeneratorExp(
        elt=Tuple(
          elts=[
            Name(
              id='i',
              ctx=Load()),
            Name(
              id='char',
              ctx=Load())],
          ctx=Load()),
        generators=[comprehension(
          target=Tuple(
            elts=[
              Name(
                id='char',
                ctx=Store()),
              Name(
                id='i',
                ctx=Store())],
            ctx=Store()),
          iter=Call(
            func=Attribute(
              value=Name(
                id='target_token_index',
                ctx=Load()),
              attr='items',
              ctx=Load()),
            args=[],
            keywords=[]),
          ifs=[],
          is_async=0)])],
      keywords=[])),
  FunctionDef(
    name='decode_sequence',
    args=arguments(
      args=[arg(
        arg='input_seq',
        annotation=None)],
      vararg=None,
      kwonlyargs=[],
      kw_defaults=[],
      kwarg=None,
      defaults=[]),
    body=[
      Assign(
        targets=[Name(
          id='states_value',
          ctx=Store())],
        value=Call(
          func=Attribute(
            value=Name(
              id='encoder_model',
              ctx=Load()),
            attr='predict',
            ctx=Load()),
          args=[Name(
            id='input_seq',
            ctx=Load())],
          keywords=[])),
      Assign(
        targets=[Name(
          id='target_seq',
          ctx=Store())],
        value=Call(
          func=Attribute(
            value=Name(
              id='np',
              ctx=Load()),
            attr='zeros',
            ctx=Load()),
          args=[Tuple(
            elts=[
              Num(n=1),
              Num(n=1),
              Name(
                id='num_decoder_tokens',
                ctx=Load())],
            ctx=Load())],
          keywords=[])),
      Assign(
        targets=[Subscript(
          value=Name(
            id='target_seq',
            ctx=Load()),
          slice=Index(value=Tuple(
            elts=[
              Num(n=0),
              Num(n=0),
              Subscript(
                value=Name(
                  id='target_token_index',
                  ctx=Load()),
                slice=Index(value=Str(s='\t')),
                ctx=Load())],
            ctx=Load())),
          ctx=Store())],
        value=Num(n=1.0)),
      Assign(
        targets=[Name(
          id='stop_condition',
          ctx=Store())],
        value=NameConstant(value=False)),
      Assign(
        targets=[Name(
          id='decoded_sentence',
          ctx=Store())],
        value=Str(s='')),
      While(
        test=UnaryOp(
          op=Not(),
          operand=Name(
            id='stop_condition',
            ctx=Load())),
        body=[
          Assign(
            targets=[Tuple(
              elts=[
                Name(
                  id='output_tokens',
                  ctx=Store()),
                Name(
                  id='h',
                  ctx=Store()),
                Name(
                  id='c',
                  ctx=Store())],
              ctx=Store())],
            value=Call(
              func=Attribute(
                value=Name(
                  id='decoder_model',
                  ctx=Load()),
                attr='predict',
                ctx=Load()),
              args=[BinOp(
                left=List(
                  elts=[Name(
                    id='target_seq',
                    ctx=Load())],
                  ctx=Load()),
                op=Add(),
                right=Name(
                  id='states_value',
                  ctx=Load()))],
              keywords=[])),
          Assign(
            targets=[Name(
              id='sampled_token_index',
              ctx=Store())],
            value=Call(
              func=Attribute(
                value=Name(
                  id='np',
                  ctx=Load()),
                attr='argmax',
                ctx=Load()),
              args=[Subscript(
                value=Name(
                  id='output_tokens',
                  ctx=Load()),
                slice=ExtSlice(dims=[
                  Index(value=Num(n=0)),
                  Index(value=UnaryOp(
                    op=USub(),
                    operand=Num(n=1))),
                  Slice(
                    lower=None,
                    upper=None,
                    step=None)]),
                ctx=Load())],
              keywords=[])),
          Assign(
            targets=[Name(
              id='sampled_char',
              ctx=Store())],
            value=Subscript(
              value=Name(
                id='reverse_target_char_index',
                ctx=Load()),
              slice=Index(value=Name(
                id='sampled_token_index',
                ctx=Load())),
              ctx=Load())),
          AugAssign(
            target=Name(
              id='decoded_sentence',
              ctx=Store()),
            op=Add(),
            value=Name(
              id='sampled_char',
              ctx=Load())),
          If(
            test=BoolOp(
              op=Or(),
              values=[
                Compare(
                  left=Name(
                    id='sampled_char',
                    ctx=Load()),
                  ops=[Eq()],
                  comparators=[Str(s='\n')]),
                Compare(
                  left=Call(
                    func=Name(
                      id='len',
                      ctx=Load()),
                    args=[Name(
                      id='decoded_sentence',
                      ctx=Load())],
                    keywords=[]),
                  ops=[Gt()],
                  comparators=[Name(
                    id='max_decoder_seq_length',
                    ctx=Load())])]),
            body=[Assign(
              targets=[Name(
                id='stop_condition',
                ctx=Store())],
              value=NameConstant(value=True))],
            orelse=[]),
          Assign(
            targets=[Name(
              id='target_seq',
              ctx=Store())],
            value=Call(
              func=Attribute(
                value=Name(
                  id='np',
                  ctx=Load()),
                attr='zeros',
                ctx=Load()),
              args=[Tuple(
                elts=[
                  Num(n=1),
                  Num(n=1),
                  Name(
                    id='num_decoder_tokens',
                    ctx=Load())],
                ctx=Load())],
              keywords=[])),
          Assign(
            targets=[Subscript(
              value=Name(
                id='target_seq',
                ctx=Load()),
              slice=Index(value=Tuple(
                elts=[
                  Num(n=0),
                  Num(n=0),
                  Name(
                    id='sampled_token_index',
                    ctx=Load())],
                ctx=Load())),
              ctx=Store())],
            value=Num(n=1.0)),
          Assign(
            targets=[Name(
              id='states_value',
              ctx=Store())],
            value=List(
              elts=[
                Name(
                  id='h',
                  ctx=Load()),
                Name(
                  id='c',
                  ctx=Load())],
              ctx=Load()))],
        orelse=[]),
      Return(value=Name(
        id='decoded_sentence',
        ctx=Load()))],
    decorator_list=[],
    returns=None),
  For(
    target=Name(
      id='seq_index',
      ctx=Store()),
    iter=Call(
      func=Name(
        id='range',
        ctx=Load()),
      args=[Num(n=100)],
      keywords=[]),
    body=[
      Assign(
        targets=[Name(
          id='input_seq',
          ctx=Store())],
        value=Subscript(
          value=Name(
            id='encoder_input_data',
            ctx=Load()),
          slice=Slice(
            lower=Name(
              id='seq_index',
              ctx=Load()),
            upper=BinOp(
              left=Name(
                id='seq_index',
                ctx=Load()),
              op=Add(),
              right=Num(n=1)),
            step=None),
          ctx=Load())),
      Assign(
        targets=[Name(
          id='decoded_sentence',
          ctx=Store())],
        value=Call(
          func=Name(
            id='decode_sequence',
            ctx=Load()),
          args=[Name(
            id='input_seq',
            ctx=Load())],
          keywords=[])),
      Expr(value=Call(
        func=Name(
          id='print',
          ctx=Load()),
        args=[Str(s='-')],
        keywords=[])),
      Expr(value=Call(
        func=Name(
          id='print',
          ctx=Load()),
        args=[
          Str(s='Input sentence:'),
          Subscript(
            value=Name(
              id='input_texts',
              ctx=Load()),
            slice=Index(value=Name(
              id='seq_index',
              ctx=Load())),
            ctx=Load())],
        keywords=[])),
      Expr(value=Call(
        func=Name(
          id='print',
          ctx=Load()),
        args=[
          Str(s='Decoded sentence:'),
          Name(
            id='decoded_sentence',
            ctx=Load())],
        keywords=[]))],
    orelse=[])])